import React from 'react';
import { motion } from 'framer-motion';
import { FaFilePdf, FaExternalLinkAlt } from 'react-icons/fa';
import { IconWrapper } from '../../utils/IconWrapper';

interface Publication {
  id: number;
  title: string;
  authors: string;
  conference: string;
  year: number;
  abstract: string;
  pdfLink?: string;
  doiLink?: string;
}

const publications: Publication[] = [
  {
    id: 1,
    title: "Beyond Copy–Pasting—Contextualizing LLMs for Secure Code Generation",
    authors: "Asadur Zaman Nabin, et al.",
    conference: "ICICS-2024",
    year: 2024,
    abstract: "This paper explores strategies for enhancing security in code generated by large language models, focusing on contextual prompting techniques that reduce vulnerabilities.",
    pdfLink: "/publications/strategic-contextualization.pdf",
    doiLink: "https://link.springer.com/chapter/10.1007/978-981-97-5791-6_15"
  },
  {
    id: 2,
    title: "Navigating the Cloud: A Review of Emerging Trends in Security",
    authors: "Asadur Zaman Nabin, et al.",
    conference: "ICSSAS-2024",
    year: 2023,
    abstract: "A comprehensive review of current security challenges and emerging solutions in cloud computing environments, with a focus on multi-tenant architectures.",
    pdfLink: "/publications/navigating-cloud.pdf",
    doiLink: "https://ieeexplore.ieee.org/abstract/document/10760612"
  },
  {
    id: 3,
    title: "PawaLLM: Unleashing the Power of LLMs in Cybersecurity",
    authors: "Asadur Zaman Nabin, et al.",
    conference: "Manuscript submitted to IEEE Transactions on Systems, Man and Cybernetics",
    year: 2023,
    abstract: "This paper presents a novel framework for leveraging large language models to enhance cybersecurity operations, including threat detection, vulnerability assessment, and incident response.",
    pdfLink: "/publications/pawallm.pdf"
  }
];

const Research: React.FC = () => {
  return (
    <section className="py-20 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <div className="inline-block">
            <h2 className="heading-xl text-primary dark:text-white mb-4 relative">
              Research & Publications
              <motion.div
                initial={{ width: 0 }}
                whileInView={{ width: "100%" }}
                transition={{ duration: 0.8, delay: 0.2 }}
                viewport={{ once: true }}
                className="h-1 bg-primary dark:bg-accent absolute bottom-0 left-0"
              ></motion.div>
            </h2>
          </div>
          <p className="text-content text-xl max-w-3xl mx-auto">
            My academic contributions in cybersecurity, cloud computing, and AI applications.
          </p>
        </motion.div>

        <div className="space-y-8">
          {publications.map((pub, index) => (
            <motion.div
              key={pub.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="bg-white p-6 rounded-lg shadow-md"
            >
              <h3 className="text-xl font-bold text-primary mb-2">{pub.title}</h3>
              <p className="text-gray-700 mb-2">{pub.authors}</p>
              <p className="text-gray-600 italic mb-4">
                {pub.conference}, {pub.year}
              </p>
              <p className="text-gray-600 mb-4">{pub.abstract}</p>
              <div className="flex space-x-4">
                {pub.pdfLink && (
                  <a 
                    href={pub.pdfLink} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="flex items-center text-accent hover:text-blue-700 transition-colors"
                  >
                    <IconWrapper icon={FaFilePdf} className="h-5 w-5 mr-2" />
                    <span>PDF</span>
                  </a>
                )}
                {pub.doiLink && (
                  <a 
                    href={pub.doiLink} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="flex items-center text-accent hover:text-blue-700 transition-colors"
                  >
                    <IconWrapper icon={FaExternalLinkAlt} className="h-4 w-4 mr-2" />
                    <span>DOI</span>
                  </a>
                )}
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          viewport={{ once: true }}
          className="mt-12 text-center"
        >
          <h3 className="text-xl font-bold text-primary mb-4">Research Interests</h3>
          <div className="flex flex-wrap justify-center gap-4">
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              Cybersecurity
            </span>
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              Blockchain Technology
            </span>
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              AI in Security
            </span>
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              Cloud Security
            </span>
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              Network Security
            </span>
            <span className="bg-white text-primary px-4 py-2 rounded-full shadow-sm">
              Secure Software Development
            </span>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default Research; 